### PR TITLE
Fix crashes when saving files from a file source

### PR DESCRIPTION
**Pull request by Silfalion**
Hey @incrediblezayed sorry for the delay, I added changes but they feel quite rough, this is just the initial logic since I didn't want to change too much without your feedback.

Ideally, I think sealed classes FileMode.byte and FileMode.file would allow the logic to be "buried" more inside the Platform handler and keep the surface code cleaner. This would need a Dart 3.0 upgrade. If you're up for that, I can make another pull request that we can merge later into this one.

### CODE REVIEW

**Comment by Silfalion** [comment]
These are the results with and without the logic:

Screenshot from 2023-09-03 10-16-34
Screenshot from 2023-09-03 10-16-52

**Comment by Silfalion** [comment]
To better test it, I added a separation for testing bytes and file savings in the example folder. Hope that's alright.

**Comment by incrediblezayed** [comment]
Hey, @Silfalion, I'll check it, test it and merge asap

**Comment by Silfalion** [comment]
Thank you:)

**Review by incrediblezayed — APPROVED** [review]
Thanks for this

**Pull request merged**
