### PR TITLE
Downgrade Android Java version to 1.8 (from 17)

### PR DESCRIPTION
**Pull request by KeeganDC**
Not sure if version 17 was needed for anything specifically but seems to run fine on lower Java version

Resolves issue https://github.com/incrediblezayed/file_saver/issues/86

### CODE REVIEW

**Review by NikolaVujovicNumarics — APPROVED** [review]

**Review by DexterZP — APPROVED** [review]

**Comment by DexterZP** [comment]
@incrediblezayed

**Comment by callmephil** [comment]
My app does not directly depend on file_saver and it's preventing me from releasing it to production since. It would be great if this PR gets merged.

**Comment by coolswood** [comment]
@incrediblezayed

**Comment by incrediblezayed** [comment]
My sincerest apologies for such delayed response, I would love to fix the issues that everyone is facing but my hands are very tied, is it possible for you guys to probably wait till next weekend? @coolswood @callmephil @DexterZP

**Comment by coolswood** [comment]
Thank you so much for your reply! Of course we can wait, we just want to understand if it will be fixed).

**Comment by incrediblezayed** [comment]
> Thank you so much for your reply! Of course we can wait, we just want to understand if it will be fixed).

Thank You so much for understanding & staying on my package, I will get this fixed soon somehow, either will merge the PR or go ahead & find something else, the java version was actually upgraded to fix an issue for certain user who requested the change, I'll see what I can do to work for both sides of the application

**Comment by Seferi** [comment]
It's been over a month since the last comment. Is there any update on this ? My CI builds are failing as well.

**Comment by incrediblezayed** [comment]
Hey, My Bad, I missed this once, I'll merge & push tonight

**Review by incrediblezayed — APPROVED** [review]

**Pull request merged**
